export const windowActionTypes = {
    SET_WINDOW_HEIGHT: 'SET_WINDOW_HEIGHT',
    SET_WINDOW_WIDTH: 'SET_WINDOW_WIDTH',
    SET_MODAL_STATE: 'SET_MODAL_STATE',
    SET_SEARCHBAR_STATE: 'SET_SEARCHBAR_STATE'
}