export const filmActionTypes = {
    FETCH_DATA_START: 'FETCH_DATA_START',
    SET_BANNER_DATA: 'SET_BANNER_DATA',
    SET_MOVIES: 'SET_MOVIES',
    START_LOADING: 'START_LOADING',
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE"
}